## Stage 1
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV production

RUN npm ci --only=production && npm cache clean --force

## Stage 2
FROM node:20-alpine AS production

WORKDIR /app

COPY --from=builder /app ./

CMD ["npm", "run", "start:prod"]
