sonar.projectKey=Insect-Trap
sonar.host.url=http://localhost:9000
sonar.token=sqa_4806fdc2bbd39171e891cbed0ed5bf23a801d571
sonar.exclusions=node_modules/*,coverage/lcov-report/*,test/*,src/*/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.scm.provider=git