import * as process from 'node:process';

export default () => ({
  appPort: parseInt(process.env.APP_PORT),
  jwtSecret: process.env.JWT_SECRET,
  jwtExpire: parseInt(process.env.JWT_EXPIRE),
  dbType: process.env.DB_TYPE,
  dbHost: process.env.DB_HOST,
  dbPort: parseInt(process.env.DB_PORT),
  dbUser: process.env.DB_USER,
  dbPassword: process.env.DB_PASSWORD,
  dbName: process.env.DB_NAME,
  timezone: process.env.TIMEZONE,
  mqttHost: process.env.MQTT_HOST,
  mqttUser: process.env.MQTT_USER,
  mqttPassword: process.env.MQTT_PASSWORD,
  redisHost: process.env.REDIS_HOST,
  redisPort: parseInt(process.env.REDIS_PORT),
  redisPassword: process.env.REDIS_PASSWORD,
  smtpHost: process.env.SMTP_HOST,
  smtpPort: parseInt(process.env.SMTP_PORT),
  smtpUsername: process.env.SMTP_USERNAME,
  smtpPassword: process.env.SMTP_PASSWORD,
  smtpMailFrom: process.env.SMTP_MAIL_FROM,
  accessTokenRedisPrefix: process.env.ACCESS_TOKEN_REDIS_PREFIX,
  originUrl: process.env.ORIGIN_URL,
  minioEndpoint: process.env.MINIO_ENDPOINT,
  minioPort: process.env.MINIO_PORT,
  minioPublicUrl: process.env.MINIO_PUBLIC_URL,
  minioAccessKey: process.env.MINIO_ACCESS_KEY,
  minioSecretKey: process.env.SECRET_KEY,
  minioBucketName: process.env.MINIO_BUCKET_NAME,
});
